handlers:
- url: '/'
  static_files: 'index.html index.htm readme.txt readme.markdown readme.md'
  upload: '.*'
- url: '/test'
  static_files: '/test/index.html'
  upload: '.*'
- url: '/'
  static_dir: '/'